import type { Mention } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getRandomAvatarUrl = () => {
  const randomIndex = Math.floor(Math.random() * PlaceHolderImages.length);
  return PlaceHolderImages[randomIndex]?.imageUrl || 'https://picsum.photos/seed/default/40/40';
};

export const mentions: Mention[] = [
  {
    id: '1',
    source: 'twitter',
    text: 'Just tried the new BrandPulse feature, and it’s a game-changer for our marketing team! So intuitive. #BrandPulse',
    author: 'Sarah K.',
    authorHandle: '@sarahk_designs',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '2',
    source: 'news',
    text: 'BrandPulse is revolutionizing how small businesses approach brand management with its new AI-powered analytics suite.',
    author: 'Tech Weekly',
    authorHandle: 'techweekly',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '3',
    source: 'blog',
    text: 'My in-depth review of BrandPulse: The good, the bad, and the brilliant. Spoiler: It’s mostly brilliant.',
    author: 'Marketing Guru',
    authorHandle: 'marketingguru',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '4',
    source: 'forum',
    text: 'Is anyone else having trouble with the reporting tool in BrandPulse? It seems to be lagging today.',
    author: 'User123',
    authorHandle: 'user123',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '5',
    source: 'twitter',
    text: 'Wow, the customer support for @BrandPulse is incredibly fast and helpful! My issue was resolved in minutes.',
    author: 'Alex Chen',
    authorHandle: '@alexchen',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '6',
    source: 'news',
    text: 'BrandPulse secures $10M in Series A funding to expand its AI capabilities and market reach.',
    author: 'VentureBeat',
    authorHandle: 'venturebeat',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '7',
    source: 'twitter',
    text: 'Not sure if BrandPulse is worth the price. The interface is clean, but I feel like I could get similar features for less.',
    author: 'Jane Doe',
    authorHandle: '@janedoe',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '8',
    source: 'blog',
    text: 'A deep dive into BrandPulse’s topic clustering feature. This is the AI magic marketers have been waiting for.',
    author: 'AI Insights',
    authorHandle: 'aiinsights',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '9',
    source: 'forum',
    text: 'How does BrandPulse compare to its main competitors? Looking for honest opinions before I subscribe.',
    author: 'Marketer22',
    authorHandle: 'marketer22',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '10',
    source: 'twitter',
    text: 'Big fan of the new dashboard layout on BrandPulse. Everything is so much easier to find now. Great UX update!',
    author: 'DesignDan',
    authorHandle: '@designdan',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
    {
    id: '11',
    source: 'twitter',
    text: 'Just started my free trial of BrandPulse. Impressed so far! The real-time tracking is super cool.',
    author: 'GrowthHacker',
    authorHandle: '@growthhack',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '12',
    source: 'news',
    text: 'Local startup BrandPulse is making waves in the marketing tech industry, challenging legacy players.',
    author: 'City Business Journal',
    authorHandle: 'citybiz',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '13',
    source: 'blog',
    text: 'Is BrandPulse the ultimate tool for reputation management? We think it might be. Here\'s why.',
    author: 'The CMO Brief',
    authorHandle: 'cmobrief',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '14',
    source: 'forum',
    text: 'The API documentation for BrandPulse is a bit confusing. Can anyone point me to some examples?',
    author: 'DevJane',
    authorHandle: 'devjane',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
  {
    id: '15',
    source: 'twitter',
    text: 'Just got an alert from BrandPulse about a spike in mentions. So helpful for staying on top of trends!',
    author: 'SocialMediaPro',
    authorHandle: '@smpro',
    avatarUrl: getRandomAvatarUrl(),
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    url: '#',
  },
];
